// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ_tdlrtLSP7DwjklAbmcvghG3CtjiiQ8',
    appId: '1:725118789084:web:01018d9b2b80a795fd5b19',
    messagingSenderId: '725118789084',
    projectId: 'automark-cs-project',
    authDomain: 'automark-cs-project.firebaseapp.com',
    storageBucket: 'automark-cs-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCql1-rJ2_wnB4zdNhK7JjOHlCCk0WIoKw',
    appId: '1:725118789084:android:367654a33ee0230bfd5b19',
    messagingSenderId: '725118789084',
    projectId: 'automark-cs-project',
    storageBucket: 'automark-cs-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXflbjHC0TnsjnzlHJxiOM4OdUwC9Hh50',
    appId: '1:725118789084:ios:602f950069d9e10bfd5b19',
    messagingSenderId: '725118789084',
    projectId: 'automark-cs-project',
    storageBucket: 'automark-cs-project.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ_tdlrtLSP7DwjklAbmcvghG3CtjiiQ8',
    appId: '1:725118789084:web:5907350a72bb2ad5fd5b19',
    messagingSenderId: '725118789084',
    projectId: 'automark-cs-project',
    authDomain: 'automark-cs-project.firebaseapp.com',
    storageBucket: 'automark-cs-project.firebasestorage.app',
  );
}
